# Generated by Django 3.2.10 on 2022-11-16 12:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BirthDayManager', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FriendDetails',
            new_name='FriendDetail',
        ),
    ]
