# Generated by Django 3.2.10 on 2022-11-17 15:19

from django.db import migrations, models
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('BirthDayManager', '0002_rename_frienddetails_frienddetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultFriend',
            fields=[
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('birth_date', models.DateField(max_length=200)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('city', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=500, null=True)),
                ('social_instagram', models.CharField(blank=True, max_length=200, null=True)),
                ('social_facebook', models.CharField(blank=True, max_length=200, null=True)),
                ('social_twitter', models.CharField(blank=True, max_length=200, null=True)),
                ('profile_image', models.ImageField(blank=True, default='profiles/default-images/user-default.png', null=True, upload_to='profiles/friends-profile/')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
