name: Birtday Tracker CI

on:
  push:
    branches: [ "master", "release" ]
  pull_request:
    branches: [ "master", "release" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Log in to GitHub Packages
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Build the Docker image
      run: |
              docker build . --file Dockerfile --tag ghcr.io/cartosat/vsw-birthday-tracker:latest
              docker push ghcr.io/cartosat/vsw-birthday-tracker:latest
