name: Birtday Tracker CI

on:
  push:
    branches: [ "master", "release" ]
  pull_request:
    branches: [ "master", "release" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
              docker build . --file Dockerfile --tag ghcr.io/cartosat/vsw-birthday-tracker:$(date +%s)
              docker run -p 8080:8000 ghcr.io/cartosat/vsw-birthday-tracker:latest
              docker push ghcr.io/cartosat/vsw-birthday-tracker:latest
