# Generated by Django 3.2.10 on 2022-11-17 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0002_alter_customuser_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='show_default_friends',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
